config/routes.rb
CafeGrader::Application.routes.draw do
  get "report/login"

  resources :contests

  resources :announcements
  resources :sites

  resources :grader_configuration, controller: 'configurations'

  root :to => 'main#login'

  match 'tasks/view/:file.:ext' => 'tasks#view'
  match 'tasks/download/:id/:file.:ext' => 'tasks#download'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

  def self.find_published(contest_started=false)
    if contest_started
      Announcement.find(:all,
                        :conditions => "(published = 1) AND (frontpage = 0)",
                        :order => "created_at DESC")
    else
      Announcement.find(:all,
                        :conditions => "(published = 1) AND (frontpage = 0) AND (contest_only = 0)",
                        :order => "created_at DESC")
    end
  end

  def self.find_for_frontpage
    Announcement.find(:all,
                      :conditions => "(published = 1) AND (frontpage = 1)",
                      :order => "created_at DESC")
  end

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController

  before_filter :admin_authorization

  in_place_edit_for :announcement, :published

  # GET /announcements
  # GET /announcements.xml
  def index
    @announcements = Announcement.find(:all,
                                       :order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.xml
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.xml
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.xml
  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        flash[:notice] = 'Announcement was successfully created.'
        format.html { redirect_to(@announcement) }
        format.xml  { render :xml => @announcement, :status => :created, :location => @announcement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.xml
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        flash[:notice] = 'Announcement was successfully updated.'
        format.html { redirect_to(@announcement) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.xml
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to(announcements_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= error_messages_for :announcement %>

<%= form_for(@announcement) do |f| %>
  <p>
    <b>Title</b><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <b>Notes</b> (shown internally, used to organize announcements)<br />
    <%= f.text_field :notes %>
  </p>

  <p>
    <b>Body</b><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <b>Author</b><br />
    <%= f.text_field :author %>
  </p>

  <p>
    <b>Published</b><br />
    <%= f.check_box :published %>
  </p>

  <p>
    <b>Show on front page?</b><br />
    <%= f.check_box :frontpage %>
  </p>

  <p>
    <b>Show only in contest?</b><br />
    <%= f.check_box :contest_only %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Listing announcements</h1>

<%= link_to 'New announcement', new_announcement_path %>

<table class="info">
  <tr class="info-head">
    <th>Updated</th>
    <th>Announcement</th>
    <th>Author</th>
    <th>Published</th>  
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% for announcement in @announcements %>
  <tr class="info-<%= cycle 'odd', 'even' %>">
    <% @announcement = announcement %>
    <td><%= time_ago_in_words announcement.updated_at %></td>
    <td>
      <% if !announcement.title.blank? %>
        <b>Title:</b> <%=h announcement.title %><br/>
      <% end %>
      <% if !announcement.notes.blank? %>
        <b>Notes: <%=h announcement.notes %></b><br/>
      <% end %>
      <%=h announcement.body %>
    </td>
    <td><%=h announcement.author %></td>
    <td><%= in_place_editor_field :announcement, :published, {}, :rows => 1 %></td>
    <td><%= link_to 'Show', announcement %></td>
    <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
    <td><%= link_to 'Destroy', announcement, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= error_messages_for :announcement %>

<%= form_for(@announcement) do |f| %>
  <p>
    <b>Title</b><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <b>Notes</b> (shown internally, used to organize announcements)<br />
    <%= f.text_field :notes %>
  </p>

  <p>
    <b>Body</b><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <b>Author</b><br />
    <%= f.text_field :author %>
  </p>

  <p>
    <b>Published</b><br />
    <%= f.check_box :published %>
  </p>

  <p>
    <b>Show on front page?</b><br />
    <%= f.check_box :frontpage %>
  </p>

  <p>
    <b>Show only in contest?</b><br />
    <%= f.check_box :contest_only %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p>
  <b>Author:</b>
  <%=h @announcement.author %>
</p>

<p>
  <b>Title:</b>
  <%=h @announcement.title %>
</p>

<p>
  <b>Notes:</b>
  <%=h @announcement.notes %>
</p>

<p>
  <b>Body:</b>
  <%=h @announcement.body %>
</p>

<p>
  <b>Published:</b>
  <%=h @announcement.published %>
</p>

<p>
  <b>Show on front page:</b>
  <%=h @announcement.frontpage %>
</p>

<p>
  <b>Show only in contest:</b>
  <%=h @announcement.contest_only %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>