config/routes.rb
CafeGrader::Application.routes.draw do
  get "report/login"

  resources :contests

  resources :announcements
  resources :sites

  resources :grader_configuration, controller: 'configurations'

  root :to => 'main#login'

  match 'tasks/view/:file.:ext' => 'tasks#view'
  match 'tasks/download/:id/:file.:ext' => 'tasks#download'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/contest.rb
class Contest < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_and_belongs_to_many :problems

  scope :enabled, :conditions => {:enabled => true}

end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController

  before_filter :admin_authorization

  in_place_edit_for :contest, :title
  in_place_edit_for :contest, :enabled

  # GET /contests
  # GET /contests.xml
  def index
    @contests = Contest.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contests }
    end
  end

  # GET /contests/1
  # GET /contests/1.xml
  def show
    @contest = Contest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contest }
    end
  end

  # GET /contests/new
  # GET /contests/new.xml
  def new
    @contest = Contest.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contest }
    end
  end

  # GET /contests/1/edit
  def edit
    @contest = Contest.find(params[:id])
  end

  # POST /contests
  # POST /contests.xml
  def create
    @contest = Contest.new(params[:contest])

    respond_to do |format|
      if @contest.save
        flash[:notice] = 'Contest was successfully created.'
        format.html { redirect_to(@contest) }
        format.xml  { render :xml => @contest, :status => :created, :location => @contest }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contests/1
  # PUT /contests/1.xml
  def update
    @contest = Contest.find(params[:id])

    respond_to do |format|
      if @contest.update_attributes(params[:contest])
        flash[:notice] = 'Contest was successfully updated.'
        format.html { redirect_to(@contest) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.xml
  def destroy
    @contest = Contest.find(params[:id])
    @contest.destroy

    respond_to do |format|
      format.html { redirect_to(contests_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= form_for(@contest) do |f| %>
  <%= f.error_messages %>

  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :title %></td>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <td></td>
      <td>
	<%= f.check_box :enabled %>
	<%= f.label :enabled %>
      </td>
    </tr>
  </table>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<h1>Listing contests</h1>

<div class="infobox">
  <b>Go back to:</b> [<%= link_to 'contest management', :controller => 'contest_management', :action => 'index' %>]
</div>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Enabled</th> 
  </tr>

<% @contests.each do |contest| %>
  <% @contest = contest %>
  <tr>
    <td><%= in_place_editor_field :contest, :name, {}, :rows => 1 %></td>
    <td><%= in_place_editor_field :contest, :title, {}, :rows => 1 %></td>
    <td><%= in_place_editor_field :contest, :enabled, {}, :rows => 1 %></td>
    <td><%= link_to 'Show', contest %></td>
    <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
    <td><%= link_to 'Destroy', contest, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New contest', new_contest_path %>

app/views/contests/new.html.erb
<h1>New contest</h1>

<%= form_for(@contest) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :enabled %><br />
    <%= f.check_box :enabled %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<h1>Contest: <%=h @contest.title %></h1>

<div class="infobox">
  <b>Go back to:</b> [<%= link_to 'contest management', :controller => 'contest_management', :action => 'index' %>]
</div>

<p>
  <b>Enabled:</b>
  <%=h @contest.enabled %>
</p>


<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>